Added histograms to visualization.
JozefStefanInstitute/factlog pull request #7
Opened 2020-08-24 15:59 UTC by Bentley386

Also removed visualization from state_graph.py since we have visualization.py for that now.

2020-08-25 10:24 UTC, aljazkosmerlj commented on stream_story_py/visualization.py
> +        if cluster > maxcluster:
Not super important, but could just do:
`if cluster not in self.labels:`

2020-08-25 10:49 UTC, aljazkosmerlj commented on stream_story_py/visualization.py
> +    #visual.get_histograms(2)
Forgotten comment? Probably should be removed.

2020-08-25 10:51 UTC, aljazkosmerlj requested changes

2020-08-25 10:51 UTC, aljazkosmerlj commented on stream_story_py/visualization.py
> +    #visual.get_histograms(2)
Forgotten comment? Probably should be removed.

2020-08-26 21:54 UTC, Bentley386 commented
Applied the requested changes in that latest commit @aljazkosmerlj

2020-09-14 09:37 UTC, merged